openapi: 3.0.0
info:
  title: Case API V2
  description: All the APIs are related to Case Attributes.
  termsOfService: ""
  version: '2.0'
  contact:
    name: UniCourt Support
    url: https://unicourt.com/contact-us
    email: support@unicourt.com
  license:
    name: UniCourt
    url: https://unicourt.com
servers:
  - url: '${SERVER_URL}'

paths:
  /articlesByDate/{articleCreatedDate}/:
    parameters:
    - in: path
      name: articleCreatedDate
      schema:
        type: string
        format: date-time
        minLength: 10
        maxLength: 10
        nullable: false
      examples:
        HTTP200-ValidDate:
          summary: ValidArticleCreatedDate
          value: "2022-09-04"
        HTTP404-InvalidCreatedDate:
          summary: InvalidCreatedDate
          value: "2022 09 04"
        HTTP404-NoResultsFoundForCreatedDate:
          summary: NoResultsFoundForCreatedDate
          value: "2025-09-04"
      required: true
      description: Retrieve the case with the specified caseId value.
    get:
      security:
        - bearerAuth: [ ]
      operationId: getArticlesByDate
      tags:
        - Python web scrapping APIs
      summary: Get all articles for given date.
      description: Gives all the parsed articles from python blogs for a given date.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              examples:
                ValidDate:
                  $ref: "#/components/examples/ArticlesByDate"
              schema:
                $ref: '#/components/schemas/ArticlesByDate'
          description: The request is received.
        '404':
          content:
            application/json:
              examples:
                InvalidCreatedDate:
                  $ref: '#/components/examples/InvalidCreatedDate'
                NoResultsFoundForCreatedDate:
                  $ref: '#/components/examples/NoResultsFoundForCreatedDate'
              schema:
                $ref: "#/components/schemas/Exception"
          description: Resource Not Found

tags:
  - name: Python web scrapping APIs
    description: "Python web scrapping APIs"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # for documentation purposes only

  examples:
    ArticlesByDate:
      value:
        object: ArticlesByDate
        articleCreatedDate: 2022-09-04
        articlesByDateArray:
          - object: Article
            title: "Python 3.13.0 alpha 1 is now available"
            releaseDate: 2022-09-04
            author: "Thomas Wouters"
            blogTime: "8:31 AM"
            createdDate: 2022-09-04
        nextPageAPI: null
        totalPages: 1
        totalCount: 1

    InvalidCreatedDate:
      value:
        object: Exception
        code: UN400
        message: INVALID_INPUT
        details: Requested articleCreatedDate is invalid.

    NoResultsFoundForCreatedDate:
      value:
        object: Exception
        code: UN400
        message: INVALID_INPUT
        details: No articles found for requested articleCreatedDate.

  schemas:
    ArticlesByDate:
      x-unicourt-container: false
      type: object
      properties:
        object:
          type: string
          description: "Array of articles posted on given date"
          default: ArticlesByDate
          minLength: 14
          maxLength: 14
          nullable: false
        articleCreatedDate:
          type: string
          format: date-time
          minLength: 10
          maxLength: 10
          example: 2022-09-04
          nullable: false
        articlesByDateArray:
          type: array
          items:
            $ref: '#/components/schemas/Article'
        nextPageAPI:
          description: Link to next page of the ArticlesByDate Results.
          example: ${SERVER_URL}/articlesByDate/2022-02-01/?pageNumber=2
          type: string
          maxLength: 255
          nullable: true
        totalPages:
          description: Total number of pages to obtain all the objects of the ArticlesByDate Results.
          example: 3
          type: integer
        totalCount:
          description: Total number of records available for this Search.
          example: 125
          type: integer
      required:
      - object
      - articleCreatedDate
      - articlesByDateArray
      - nextPageAPI
      - totalPages
      - totalCount

    Article:
      x-unicourt-container: false
      title: Article
      type: object
      nullable: true
      properties:
        object:
          type: string
          description: Name of the object
          default: Article
          minLength: 7
          maxLength: 7
          nullable: false
        title:
          type: string
          minLength: 3
          maxLength: 200
          nullable: false
          example: "Python 3.13.0 alpha 1 is now available"
        releaseDate:
          type: string
          format: date-time
          minLength: 10
          maxLength: 10
          example: 2022-09-04
          nullable: false
        author:
          type: string
          minLength: 3
          maxLength: 50
          example: "Thomas Wouters"
          nullable: false
        blogTime:
          type: string
          minLength: 7
          maxLength: 8
          example: "8:31 AM"
          nullable: true
        createdDate:
          type: string
          format: date-time
          minLength: 10
          maxLength: 10
          example: 2022-09-04
          nullable: false
      required:
        - object
        - title
        - releaseDate
        - author
        - blogTime
        - createdDate

    Exception:
      title: Exception
      type: object
      description: Exception object contains specific error code and its message related to the API request validation error or error occurred during API request processing.
      nullable: True
      properties:
        object:
          type: string
          example: Exception
          default: Exception
          minLength: 9
          maxLength: 9
          nullable: False
        code:
          type: string
          description: Indicates the type of error occurred.
          minLength: 1
          maxLength: 75
          nullable: False
        message:
          type: string
          description: Indicates the error message that describes the error code.
          minLength: 1
          maxLength: 255
          nullable: False
        details:
          type: string
          description: Describes what went wrong.
          minLength: 1
          maxLength: 255
          nullable: False
      required:
        - object
        - code
        - message
        - details
